# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ollie < Formula
  desc ""
  homepage ""
  version "0.1.4"

  depends_on "git" if OS.mac?
  depends_on :macos

  on_intel do
    url "https://github.com/TeamGoodOnes/ollie-cli/releases/download/v0.1.4/ollie-cli_Darwin_x86_64.tar.gz",
      headers: [
        "Accept: application/octet-stream",
        "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
      ]
    sha256 "84f6c5b303dc96d9d1ab6e1503e53d0d572fee8154ab63c99c8277b06eef0f13"

    def install
      bin.install "ollie"
    end
  end
  on_arm do
    url "https://github.com/TeamGoodOnes/ollie-cli/releases/download/v0.1.4/ollie-cli_Darwin_arm64.tar.gz",
      headers: [
        "Accept: application/octet-stream",
        "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
      ]
    sha256 "b33caf4238fe24f1dfd77e82730e33a83f589e8418b0e8b3e6ce89482dd7f2e5"

    def install
      bin.install "ollie"
    end
  end
end
